"""try

Revision ID: 8295c68cf5e7
Revises: d4df6eab5f5f
Create Date: 2024-03-14 00:13:11.598249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8295c68cf5e7'
down_revision = 'd4df6eab5f5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
