"""submitter

Revision ID: d5e72e584482
Revises: 8295c68cf5e7
Create Date: 2024-03-17 00:38:40.580528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e72e584482'
down_revision = '8295c68cf5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('submitter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'submitter')
    # ### end Alembic commands ###
